### PR TITLE
UI and web3

### PR DESCRIPTION
**Pull request by jakai7**
Changed UI layout and integrated Polkadot browser extension.

### CODE REVIEW

**Comment by musnit** [comment]
@martink-rsa plz review

**Comment by jakai7** [comment]
Hi guys, sorry for the delay on this, I was trying to figure out why the polkadotjs api was not connecting with the Netlify deploy but it was working locally. @vgeddes thank you for fixing the polkadotjs dependencies solved it the issue.

**Comment by jakai7** [comment]
@martink-rsa please check if I am using React properly.

**Comment by jakai7** [comment]
@vgeddes @martink-rsa please let me know if I can merge this.

**Comment by vgeddes** [comment]
@jakai7 looks good! One problem is that I saw quite a few lint errors and warnings in the logs after running `yarn start`. Hoping you can tackle those before merging. Or at least cut issues to track them 🙂

**Comment by jakai7** [comment]
@vgeddes I fixed the lint warnings, thanks for pointing them out. 

Ready to Merge :smiley:

**Pull request merged**
