### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by jakai7**

### CODE REVIEW

**Review by philipstanislaus — APPROVED** [review]

**Comment by musnit** [comment]
why are we even testing/incorporating ganache into the frontend? isn't metamask fine?

**Comment by jakai7** [comment]
> why are we even testing with/incorporating ganache into the frontend? isn't metamask fine?

I added ganache-core as a dev-dependency so that I can test some of the bridge functionality without depending on the UI/Browser code because sometimes it is difficult to know where the errors are coming from, It is also helpful when adding new bridge functions that interact with the Ethereum blockchain.

**Comment by musnit** [comment]
makes sense, though you're importing it in a production file so it's not really a dev dependency. could we interact with it from a separate file that's not part of the production flow?

**Comment by jakai7** [comment]
> could we interact with it from a separate file that's not part of the production flow?
Good idea. I will not merge this branch. I will keep it to reference it later when I will revisit this.

**Pull request closed without merging**
